WycliffeAssociates/translationExchange

src/js/pages/takes/TakeContainer.js
src/js/pages/takes/components/AudioComponent.js

new AudioComponent appears when source audio button is clicked. For now it contains the same audio as the regular player
EDIT: Also resized the AudioComponent to allow both to display on same screen

Displays new AudioComponent with source

---

src/js/pages/chapters/ProjectContainer.js
src/js/pages/chapters/components/ChapterList.js
src/js/pages/takes/ChapterContainer.js
src/js/pages/takes/components/Take.js

Posts request in ProjectContainer for chapter information, and then Chapter and Take pages are populated with data from the server. 
Path redirect hardcoded

Retrieves available chapters and displays corresponding data

---

src/js/pages/chapters/components/ChapterList.js
src/js/pages/takes/TakeContainer.js
src/js/pages/takes/components/Take.js
src/js/pages/takes/components/TakeList.js

Gets Source Audio from database (if present)
*also, added return statement to parseDate() function in ChapterList to avoid Date error we were getting

Retrieves Source Audio from database and displays it

---

src/js/pages/projects/components/ProjectsList.js

Date when displaying available projected is now parsed

Added parseDate() to ProjectsList.js

---

src/js/pages/takes/components/Take.js

Source audio from database combined with logic that only displays source audio button if source audio is present

Retrieve source audio

---

src/js/pages/chapters/components/ChapterList.js
src/js/pages/projects/components/ProjectsList.js
src/js/pages/takes/ChapterContainer.js
src/js/pages/takes/TakeContainer.js
src/js/pages/takes/components/AudioComponent.js
src/js/pages/takes/components/Chunk.js
src/js/pages/takes/components/Take.js

Takes files marked as 'Export' and plays them in order, also has source audio option.

Added AudioComponent to bottom of each chunklist

---

src/js/pages/chapters/ProjectContainer.js
src/js/pages/chapters/components/ChapterList.js
src/js/pages/takes/components/Chunk.js
src/js/pages/takes/components/CommentsButton.js
src/js/pages/takes/components/ExportButton.js
src/js/pages/takes/components/MarkAsDone.js
src/js/pages/takes/components/Star.js

added button for publishing

---

src/config/config.js
src/js/pages/chapters/ProjectContainer.js
src/js/pages/chapters/components/ChapterList.js
src/js/pages/projects/FilterContainer.js
src/js/pages/projects/ProjectsListContainer.js
src/js/pages/projects/components/ProjectsList.js
src/js/pages/takes/ChapterContainer.js
src/js/pages/takes/components/StitchTakes.js
src/js/pages/takes/components/Take.js

working with new API except timestamps, is_publish/is_export, and updating takes

mostly working with new api

---

src/js/pages/takes/TakeContainer.js
src/js/pages/takes/components/Chunk.js
src/js/pages/takes/components/TakeList.js
src/js/pages/takes/components/TakeTable.js
src/js/pages/takes/components/comments/RecordComment.css
src/js/pages/takes/components/comments/RecordComment.js

Open chunk accordions no longer overlap the next chunk title. Also, a blue circle in the background of the audio comment stop button is gone

Fixed Spacing issue and Comment button bug

---

src/js/pages/Login/AvailableUsers.js
src/js/pages/Login/components/RedoButton.js
src/js/pages/Login/components/UserCard.js
src/js/pages/Login/components/YesButton.js
src/js/pages/user/components/BottomButtons.js
src/js/pages/user/components/CreateUser.js

test this implementation, and new style

Merge ns_te_dev, add new styles for user card

---

src/js/pages/chapters/components/ChapterCard.js
src/js/pages/projects/components/ProjectCard.js

fix the alignment of the icons in the chapter and project cards

Ns fix button alignment

---

src/js/pages/chapters/ChaptersPage.js
src/js/pages/chapters/components/ChapterCard.js

some small styling fixes to the chapter page

chapter page styling fixes

---

src/js/actions/UserActions.js

- changed requests on user actions 
iconHash-> icon_hash
nameAudio-> name_audio
- these changes are going to work with dev branch on the backend.

changed requests on user actions

---

src/js/actions/UserActions.js
src/js/pages/chapters/components/ChapterCard.js
src/js/pages/projects/MyProjectsContainer.js
src/js/pages/projects/components/ProjectCard.js

- added a warning sign on the chapter card when the chapter is not fully uploaded.

warning sign added on chapter card when is not fully uploaded

---

src/css/chapters.css
src/js/actions/UserActions.js
src/js/pages/chapters/ChaptersPage.js
src/js/pages/chapters/components/ChapterCard.js

Relayout chapter page to have alternating cards numbers in rows.
Added necessary css and media queries to produce required effect.

relaying out chapter page

---

src/js/components/NavBar.js
src/js/pages/KanbanBoard/KanbanPage.js
src/js/pages/KanbanBoard/components/UtilityPanel/UtilityPanel.js
src/js/pages/chapters/components/ChapterCard.js
src/js/pages/projects/MyProjectsContainer.js
src/js/pages/projects/components/ProjectCard.js

-Refactor made to be ready for verse mode.

Jl verse mode

---

src/js/actions/AuthActions.js
src/js/actions/CommentsActions.js
src/js/actions/UserActions.js
src/js/components/Loading.js
src/js/pages/KanbanBoard/KanbanPage.js
src/js/pages/KanbanBoard/components/KanbanColumn.js
src/js/pages/KanbanBoard/components/RecordCommentsComponents/Comments.js
src/js/pages/KanbanBoard/components/RecordCommentsComponents/RecordCommentsModal.js
src/js/pages/Login/AvailableUsers.js
src/js/pages/Login/components/WelcomeComponent.js
src/js/pages/chapters/components/ChapterCard.js
src/js/reducers/reducer.js

A little bit of cleanup in the following areas
1) remove console.logs
2) temporary redirect users to projects upon book completion
3) clean up formatting
4) add height prop to loading component
5) styling fixes

redirect completed books,remve console logs

---

src/config/config.js
src/css/takes.css
src/js/components/DragHereBox.js
src/js/components/Loading.js
src/js/pages/KanbanBoard/KanbanPage.js
src/js/pages/KanbanBoard/components/KanbanBoard.js
src/js/pages/KanbanBoard/components/UtilityPanel/UtilityPanel.js
src/js/pages/chapters/ChaptersPage.js
src/js/pages/chapters/components/ChapterCard.js
src/js/pages/takes/newComponents/TakeCard/TakeCardComponents/TakeCardTopIcon.js
src/js/pages/user/components/CreateUserContainer.js
src/js/pages/user/components/RecordButton.js

1) some css fixes for misaligned components
2) add missing material_icons
3) add logic to check for published takes that have a rating lower than 3.
4) add line to config file for redirect on VM for GitHub login

Ns css fixes

---

src/config/config.js
src/js/pages/chapters/components/ChapterCard.js
src/js/pages/takes/components/audioplayer/Waveform.js
src/js/pages/takes/newComponents/TakeCard/TakeCard.js

Fix issue with take card playing when clicking anywhere after initial play through.
Adjust chapter page layout for some screen dimensions

Ns fix take player reset

---

src/js/pages/KanbanBoard/components/KanbanColumn.js
src/js/pages/takes/components/audioplayer/Waveform.js
src/js/pages/takes/newComponents/TakeCard/TakeCard.js

Add logic that redirects a user to a chunk without a published take 
when the user clicks on the next chunk button on the last chunk of a chapter

Ns next chunk last chunk

---

package.json
src/css/takes.css
src/js/pages/KanbanBoard/components/KanbanBoard.js
src/js/pages/takes/TakeCard/Components/Comments.js
src/js/pages/takes/TakeCard/Components/TakeCard.js
src/js/pages/takes/TakeCard/index.js

update toast library to allow for positioning and customization of toast notifications.
remove legacy toast library
small css edit to toggle component

update toast library

---

src/App.css
src/App.js
src/css/notification.css
src/js/actions/KanbanPageActions.js
src/js/pages/KanbanBoard/KanbanPage.js
src/js/pages/KanbanBoard/components/DeleteTake.js
src/js/pages/KanbanBoard/components/KanbanBoard.js
src/js/pages/KanbanBoard/components/KanbanColumn.js
src/js/pages/takes/TakeCard/Components/BottomButtons.js
src/js/pages/takes/TakeCard/Components/TakeCard.js
src/js/pages/takes/TakeCard/Components/TopBar.js
src/js/pages/takes/TakeCard/index.js
src/languages/textToDisplay.json

1) add actions for take deletion
2) create drop target for take deletion
3) add logic to handle take deletion/undo take deletion
4) remove legacy toast references
5) remove console.logs
6) add localized/translated text
7) small css fixes

Ns delete take

---

public/index.html
src/js/components/PlayerTracker.js
src/js/pages/KanbanBoard/components/RecordCommentsComponents/WaveForm.js
src/js/pages/takes/TakeCard/Components/CommentRow.js
src/js/pages/takes/TakeCard/Components/Comments.js
src/js/pages/takes/TakeCard/Components/TakeCard.js
src/languages/textToDisplay.json

1) Increase frequency of onProgress callback in ReactPlayer to improve comment scrubbing
2) remove padding around comments in take card
3) add overflow scroll for take card comments
4) style take card comments scroll track bar
5) edit player tracker position in firefox
6) remove tether script.
7) center waveform for recordCommentsModal

Ns player rewind

---

src/config/config.js
src/css/dropdown.css
src/js/components/NavBar.js

1. fixed overflow-y problem (Pslams 119).
2. styled dropdown.
3. Marked (change of color) published chunk on dropdown.

Jl dropdown fix

---

src/js/components/NavBar.js
src/js/pages/KanbanBoard/components/UtilityPanel/UtilityPanel.js

small fix for projects in verses

small fix for projects in verses

---

src/config/config.js

correctly configure config to work on vm

uncomment config for vm

---

src/__test__/test_container/scripts/AudioContext.js
src/__test__/test_container/test-runner.yml
src/__test__/unit_tests/pages/projects/components/ProjectCard.test.js
src/js/pages/projects/components/ProjectCard.js

1) allow user to navigate to project by clicking anywhere on the card
2) add displayNames to ProjectCard styled components for testing
3) add test for ProjectCard Component
4) edit test-runner to resolve audio context error

Ns project card

---

src/css/dropdown.css
src/js/components/NavBar.js

Add a check mark to the published takes in the dropdown menu

add icon to published in dropdown

---

src/js/pages/KanbanBoard/components/RecordCommentsComponents/RecordCommentsModal.js
src/js/pages/KanbanBoard/components/RecordCommentsComponents/WaveForm.js

Fix bug where ReactMic was still recording even after Recording Comments Modal was closed. 
1) add logic to check if stop has been clicked by user
2) add setTimeout to ensure state gets reset, and onStop() is called, before the modal is closed.

Ns record modal fix

---

src/__test__/unit_tests/actions/KanbanPageActions.test.js
src/js/actions/KanbanPageActions.js
src/js/pages/KanbanBoard/KanbanPage.js
src/js/pages/KanbanBoard/components/KanbanColumn.js
src/js/pages/KanbanBoard/components/RecordCommentsComponents/RecordCommentsModal.js
src/js/pages/takes/TakeCard/Components/TakeCard.js
src/js/pages/takes/components/audioplayer/Waveform.js
src/js/reducers/KanbanPageReducer.js

1) fix issue with multiple takes playing
2) fix issue with waveform resetting to start of audio on pause
3) add test for new action
4) fix incorrect string from PR #460

Ns multiple takes playing

---

src/__test__/unit_tests/pages/KanbanBoard/components/DeleteTake.test.js
src/__test__/unit_tests/pages/KanbanBoard/components/__snapshots__/DeleteTake.test.js.snap
src/js/pages/KanbanBoard/components/DeleteTake.js
src/js/pages/takes/TakeCard/Components/DragTarget.js
src/js/pages/takes/TakeCard/Components/TakeCard.js
src/js/pages/takes/TakeCard/Components/TopBar.js
src/languages/textToDisplay.json

Make changes to the Delete Take Drop Target in order for the 
delete action visual feedback to be activated on TakeCard Edge touching the drop target.

Ns card edge

---

src/js/actions/KanbanPageActions.js
src/js/localState.js
src/js/pages/chapters/components/ChapterCard.js
src/js/reducers/KanbanPageReducer.js
src/js/store.js
src/languages/textToDisplay.json

1) Add KanbanPage state to local storage to allow user to remain on the chunk that they are 
working on after page refresh.
2) Restate localStorage on navigation to newChapter

Ns state locally

---

src/__test__/unit_tests/actions/KanbanPageActions.test.js
src/__test__/unit_tests/pages/Login/components/WelcomeComponent.test.js
src/js/actions/KanbanPageActions.js
src/js/pages/KanbanBoard/KanbanPage.js
src/js/pages/KanbanBoard/components/KanbanColumn.js
src/js/pages/KanbanBoard/components/RecordCommentsComponents/Player.js
src/js/pages/Login/AvailableUsers.js
src/js/pages/Login/components/WelcomeComponent.js
src/js/pages/takes/TakeCard/Components/CommentRow.js
src/js/pages/takes/TakeCard/Components/DragTarget.js
src/js/pages/takes/TakeCard/Components/TakeCard.js
src/js/pages/takes/TakeCard/Components/TopBar.js
src/js/pages/takes/TakeCard/index.js
src/js/pages/tasks/components/TaskIdenticon.js
src/js/pages/user/components/BottomSection.js
src/js/reducers/KanbanPageReducer.js

1) add user owner for take cards
2) add checks for take and comment owners
3) update individual take card owners, not every single take card with the same icon.
4) add real take card dates to takes (replace placeholder)

Ns take card user

---

src/js/pages/takes/TakeCard/Components/Comments.js
src/js/pages/takes/TakeCard/Components/TopBar.js
src/js/pages/takes/TakeCard/index.js

1) fix wrong user bug on take card
2) reduce size of record button on take card

Ns take card fixes

---

.travis.yml
sonar-project.properties

Nd sonar scan

---

src/__test__/unit_tests/components/BorderButton.test.js
src/__test__/unit_tests/pages/ExportPage/ExportPage.test.js
src/__test__/unit_tests/pages/ExportPage/components/ChapterSelected.test.js
src/__test__/unit_tests/pages/ExportPage/components/CompletedCheckbox.test.js
src/__test__/unit_tests/pages/ExportPage/components/Downloading.test.js
src/__test__/unit_tests/pages/ExportPage/components/ExportCard.test.js
src/__test__/unit_tests/pages/ExportPage/components/ExportProject.test.js
src/__test__/unit_tests/pages/ExportPage/components/Footer.test.js
src/__test__/unit_tests/pages/ExportPage/components/LoadingMp3.test.js
src/__test__/unit_tests/pages/ExportPage/components/LoadingWav.test.js
src/js/components/BorderButton.js
src/js/pages/export/ExportPage.js
src/js/pages/export/components/ChapterSelected.js
src/js/pages/export/components/CompletedCheckbox.js
src/js/pages/export/components/Downloading.js
src/js/pages/export/components/ExportCard.js
src/js/pages/export/components/ExportProject.js
src/js/pages/export/components/Footer.js
src/js/pages/export/components/LoadingMp3.js
src/js/pages/export/components/LoadingWav.js

-tests added to export page components

tests to export page added

---

src/js/actions/ExportPageActions.js
src/js/components/BorderButton.js
src/js/pages/export/ExportPage.js
src/js/pages/export/components/CompletedCheckbox.js
src/js/pages/export/components/ExportCard.js
src/js/pages/projects/MyProjectsContainer.js
src/js/pages/projects/ProjectPage.js
src/js/pages/projects/components/DownloadingTransfer.js
src/js/pages/projects/components/ExportModal.js
src/js/pages/projects/components/LoadingTransfer.js
src/js/pages/projects/components/ProjectCard.js
src/js/reducers/ExportPageReducer.js

- transfer functionality added (animations, steps, buttons etc..) 
- refactored export modal states to redux.
- Export checkbox disabled when there are not completed chapters.

Jl transfer

---

src/js/pages/projects/ProjectPage.js

uncomment fetch projects

---

src/js/pages/projects/MyProjectsContainer.js

fix passing down of some props

add history and action to child

---

src/js/actions/ProjectsPageActions.js

edit timeout

---

src/App.css
src/__test__/unit_tests/pages/ChapterReview/components/BottomBar/ControlButtons.test.js
src/__test__/unit_tests/pages/ChapterReview/index.test.js
src/__test__/unit_tests/pages/KanbanBoard/components/ReviewDialog.test.js
src/index.css
src/js/pages/ChapterReview/components/BottomBar/ControlButtons.js
src/js/pages/ChapterReview/components/BottomBar/index.js
src/js/pages/ChapterReview/components/ReviewColumn/SelectedTake.js
src/js/pages/ChapterReview/components/ReviewColumn/index.js
src/js/pages/ChapterReview/components/Take/index.js
src/js/pages/ChapterReview/index.js
src/js/pages/KanbanBoard/components/KanbanColumn.js
src/js/pages/KanbanBoard/components/ReviewDialog.js
src/languages/textToDisplay.json

1) make text unselectable to improve UI
2) allow user navigation in chapter review by touching the take card
3) add alternate form of navigation into chapter reivew
4) add/edit tests

Ns te fixes

---

src/js/pages/KanbanBoard/components/KanbanColumn.js

-fix bug that was resulting in wrong takes being loaded for chunks
-modify navigateToChapter function and adjust into nextChapter() function

wrong id on chapter navigation
